export const GET_REQUEST_PLACE = "GET_REQUEST_PLACE";
export const GET_REQUEST_PENDING = "GET_REQUEST_PENDING";
export const GET_REQUEST_SUCCEEDED = "GET_REQUEST_SUCCEEDED";
export const GET_REQUEST_FAILED = "GET_REQUEST_FAILED";
export const SCREEN_CHANGED = "SCREEN_CHANGED";