export const GET_REQUEST_PLACE = "GET_REQUEST_PLACE";
export const GET_REQUEST_REVIEW = "GET_REQUEST_REVIEW";
export const GET_REQUEST_PENDING = "GET_REQUEST_PENDING";
export const GET_REQUEST_PLACE_SUCCEEDED = "GET_REQUEST_PLACE_SUCCEEDED";
export const GET_REQUEST_REVIEW_SUCCEEDED = "GET_REQUEST_REVIEW_SUCCEEDED"
export const GET_REQUEST_FAILED = "GET_REQUEST_FAILED";
export const SCREEN_CHANGED = "SCREEN_CHANGED";




